[package]
name = "spyne"
version = "0.2.0"
edition = "2024"
description = "All-in-one toolkit"
license = "MIT"

[dependencies]
spyne-macros = { path = "../spyne-macros" }
spyne-quote = { path = "../spyne-quote" }
spyne-syntax = { path = "../spyne-syntax" }

[features]
primitives = []
macros = []

text-gapbuffer = ["text"]
text-cursor = ["text"]
text = []

serialization-binary = ["serialization"]
serialization = []

macros-quote = []
macros-serialization = ["serialization", "serialization-binary"]