[package]
name = "spyne"
version = "0.2.0"
edition = "2024"
description = "All-in-one toolkit"
license = "MIT"

[dependencies]
spyne-macros = { path = "../spyne-macros" }
spyne-quote = { path = "../spyne-quote" }
spyne-syntax = { path = "../spyne-syntax" }

[features]
macros = []
primitives = []

macros-quote = ["primitives-syntax"]
macros-serialization = ["primitives-serialization", "primitives-serialization-binary"]

primitives-serialization = []
primitives-serialization-binary = ["primitives-serialization"]

primitives-syntax = []
primitives-syntax-ast = ["primitives-syntax"]
primitives-syntax-tokgen = ["primitives-syntax"]
primitives-syntax-token = ["primitives-syntax"]

primitives-text = []
primitives-text-gapbuffer = ["primitives-text"]
primitives-text-cursor = ["primitives-text"]