[package]
name = "spyne-macros"
version = "0.1.1"
edition = "2024"
description = "Macros for the spyne crate"
license = "MIT"

[dependencies]
spyne-quote = { path = "../spyne-quote" }
spyne-syntax = { path = "../spyne-syntax" }

[lib]
proc-macro = true