[package]
name = "spyne-macros"
version = "0.1.1"
edition = "2024"
description = "Macros for the spyne crate"
license = "MIT"

[dependencies]
spyne-quote = "0.1.6"
spyne-syntax = "0.1.3"

[lib]
proc-macro = true