[package]
name = "spyne-quote"
version = "0.1.6"
edition = "2024"
description = "Quasi-quoting macro for the spyne crate"
license = "MIT"

[dependencies]
spyne-syntax = "0.1.3"

[lib]
proc-macro = true