[package]
name = "spyne-quote"
version = "0.1.5"
edition = "2024"
description = "Quasi-quoting macro for the spyne crate"
license = "MIT"

[dependencies]
spyne-syntax = "0.1.1"

[lib]
proc-macro = true